export const AUDIO_LANGUAGES = [
  { code: 'hinglish', label: 'Hinglish' },
  { code: 'english', label: 'English' },
  { code: 'hindi', label: 'Hindi' },
  { code: 'telugu', label: 'Telugu' },
  { code: 'tamil', label: 'Tamil' },
  { code: 'kannada', label: 'Kannada' },
  { code: 'malayalam', label: 'Malayalam' },
  { code: 'bengali', label: 'Bengali' },
  { code: 'marathi', label: 'Marathi' },
  { code: 'gujarati', label: 'Gujarati' },
  { code: 'punjabi', label: 'Punjabi' },
  { code: 'spanish', label: 'Spanish' },
  { code: 'french', label: 'French' },
  { code: 'german', label: 'German' },
  { code: 'japanese', label: 'Japanese' },
  { code: 'korean', label: 'Korean' },
  { code: 'arabic', label: 'Arabic' },
  { code: 'portuguese', label: 'Portuguese' },
  { code: 'italian', label: 'Italian' },
  { code: 'chinese', label: 'Chinese' },
];
